name: "Main"

on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  # ARM_USE_OIDC: true
  
  # Variables
  TF_VAR_subscription_id: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  TF_VAR_resource_group_name: "devops-intern-sandbox-rg-sandbox-sea"
  TF_VAR_project_name: "azure-e2e-devops"
  TF_VAR_location: "southeastasia"
  TF_VAR_key_vault_name: "rg-intern-devops"
  TF_VAR_allowed_ip: "0.0.0.0/0"
  TF_VAR_address_space: '["10.0.0.0/16"]'
  TF_VAR_address_prefixes: '["10.0.0.0/28"]'

jobs:
  lint:
    name: 'Running ESlint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up NodeJs
        uses: actions/setup-node@v4
        with: 
          node-version: '20'

      - name: Install Dependencies
        run: npm ci
        working-directory: ./app

      - name: Run ESlint
        id: lint
        run: npx eslint index.html
        working-directory: ./app

      - name: Success Message
        if: ${{ steps.lint.outcome == 'success' }}
        run: echo "Success"

  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    env:
      ARM_SKIP_PROVIDER_REGISTRATION: true
    outputs:
      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Add az login because cannot create "Federated Credential"
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with: 
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ./terraform

    - name: Terraform Plan
      id: tf-plan
      run: |
        export exitcode=0
        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?

        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT

        if [ $exitcode -eq 1 ]; then
          echo Terraform Plan Failed!
          exit 1
        else 
          exit 0
        fi
      working-directory: ./terraform

    - name: Publish Terraform Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: |
          ./terraform/tfplan
          ./terraform/.terraform.lock.hcl

    - name: Create String Output
      id: tf-plan-string
      run: |
        TERRAFORM_PLAN=$(terraform show -no-color tfplan)

        delimiter="$(openssl rand -hex 8)"
        echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
        echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
        echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo '```terraform' >> $GITHUB_OUTPUT
        echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
        echo '```' >> $GITHUB_OUTPUT
        echo "</details>" >> $GITHUB_OUTPUT
        echo "${delimiter}" >> $GITHUB_OUTPUT
      working-directory: ./terraform
    
    - name: Publish Terraform Plan to Task Summary
      env: 
        SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
      run: |
        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

    - name: Push Terraform Output to PR
      if: github.ref != 'refs/heads/main'
      uses: actions/github-script@v7
      env:
        SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const body = `${process.env.SUMMARY}`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          })

  terraform-apply:
    name: Terraform Apply
    if: github.ref == 'refs/heads/main' && needs.terraform-plan.outputs.tfplanExitCode == 2
    runs-on: ubuntu-latest
    environment: production
    needs: [terraform-plan]

    outputs:
      vm_pub_ip: ${{ steps.get_ip.outputs.VM_PUB_IP }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download Terraform Plan
      uses: actions/download-artifact@v4
      with:
        name: tfplan
        path: ./terraform

    # Add az login because cannot create "Federated Credential"
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./terraform

    - name: Terraform Output
      id: get_ip
      run: |
        PUB_IP=$(terraform output -raw vm_pub_ip )
        
        echo "VM Public IP : $PUB_IP"
        echo "VM_PUB_IP=$PUB_IP" >> $GITHUB_OUTPUT
      working-directory: ./terraform

  build-and-apply:
    name: Build & Push Docker
    needs: [terraform-apply]
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Add az login because cannot create "Federated Credential"
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: Get ACR Name
      id: get_acr
      run: |
        SEARCH_TERM="szuryuu"

        echo "Finding acr contains $SEARCH_TERM"

        ACR_NAME=$(az acr list \
          --resource-group devops-intern-sandbox-rg-sandbox-sea \
          --query "[?contains(name, '$SEARCH_TERM')].loginServer" \
          -o tsv | head -n 1
        )

        if [ -z "$ACR_NAME" ]; then
          echo "ACR not found..."
          az acr list --resource-group devops-intern-sandbox-rg-sandbox-sea -o table

          exit 1
        fi

        echo "ACR_LOGIN_SERVER=$ACR_NAME" >> $GITHUB_ENV
        echo "ACR name found: $ACR_NAME"

    - name: ACR Login
      run: az acr login --name $(echo $ACR_LOGIN_SERVER | cut -d. -f1)

    - name: Build and Push to ACR
      uses: docker/build-push-action@v5
      with:
        context: ./app
        push: true
        tags: ${{ env.ACR_LOGIN_SERVER }}/my-webapp:latest

    - name: Smoke Test
      run: ./scripts/smoke_test.sh ${{ needs.terraform-apply.outputs.vm_pub_ip }}
